### ISSUE TITLE
Subplot structure inside fig 

### ISSUE THREAD

**Issue by vedantsingh1404** [rajp152k/Compilers-II#3]
Think of a good way to implement the subplot functionality.

**Comment by vedantsingh1404** [comment]
Maybe we can do 
```
fig a {
    size <- 2, 2 [attr list] 
    subplot b {
        .
        .
        .
    }
    ... 3 more such subplots
}
```
[attr list] contains attributes similar to the ones in matplotlib. 
When size is not mentioned, we simply disallow the creation of subplots inside the figure.

**Comment by rajp152k** [comment]
add iteration facilities for subplots : 

replace b with index : eg [0][1]
