### ISSUE TITLE
issues in parsing

### ISSUE THREAD

**Issue by karan121bhukar** [rajp152k/Compilers-II#36]
sometimes functions as sin tan cos etc are considered as local variable and gives error as undefined variable 
ex : y := (EXP ^ sin(x)) -2 * cos(4*x) 
gives sin as undefined variable.

**Comment by rajp152k** [comment]
some details identified; 

root cause : ambiguity for LALR algo

Earley algorithm(default for lark) handles it but does not allow an embedded tree.

will need a transformer rewrite for the earley algorithm : performance will take a hit.

**Comment by rajp152k** [comment]
documenting reproducibility:

stand alone functions are not identified: sin(x),cos(x)
but an extra set of parentheses passes

**Comment by rajp152k** [comment]
conceptual fix : create a new rule for a compound function : do not include with atomic expressions.

Quick fix ??

**Comment by rajp152k** [comment]
Quick fix : grouped the alias for func expr with sum expression 

awaiting pull request...

**Comment by rajp152k** [comment]
solved by the quick fix
