### ISSUE TITLE
range statement

### ISSUE THREAD

**Issue by rajp152k** [rajp152k/Compilers-II#4]
Creating a new issue for every distinct idea in language design to avoid mix-ups: use language-design labels from now onwards

**Comment by rajp152k** [comment]
Ideas on the Range statement:

```
range_stmt:  [range_descriptor] range_ends
range_ends: number 'to' number
range_descriptor: 
     number 'in'       # to deal with discretes
   | 'continuous' ':'  # use a high number (sensible default) for number above to get a continuous view

seems better than a post attr_list in this case to aid readability

**Comment by vedantsingh1404** [comment]
We can even use an interval feature that plots the graph at given intervals in the range and not continuously.

**Comment by rajp152k** [comment]
yeah, that's what I was thinking with the first part of the descriptor:

say `10 in 0 to 1` makes a linear spacing as [0, 0.1,0.2 ..... 0.9]

the continuous one would just replace that 10 with a high sensible default to avoid the user from having to decide.
