### ISSUE TITLE
Attribute List syntax

### ISSUE THREAD

**Issue by vedantsingh1404** [rajp152k/Compilers-II#5]
Have to decide the syntax for the attribute list used while defining the plots.

```
attr1 = val
```
**OR**
```
attr1: val
```
**OR**
```
attr1 <- val
```
**OR** 
any other idea that you may have.

**Comment by PanchalShubham** [comment]
2nd one is I guess more convenient

**Comment by vedantsingh1404** [comment]
Yeah, even I prefer the second one. Mainly because it is different from the python syntax.

**Comment by vedantsingh1404** [comment]
@rajp152k Should we make this a dictionary instead of a list?

**Comment by rajp152k** [comment]
Yes, that way we don't have to enforce an order

**Comment by rajp152k** [comment]
And error checking would be more sensible

**Comment by vedantsingh1404** [comment]
Yeah right.
